// SLAB: mass conversion of "struct page" to "struct slab"
//
// usage:
// spatch --include-headers --no-includes slab.cocci mm/slab.c

// various API changes - account_slab()
@ convert_callers_account_slab @
expression E;
@@
-account_slab_page(
+account_slab(
- page
+ slab
  ,...)

// various API changes - unaccount_slab()
@ convert_callers_unaccount_slab @
expression E;
@@
-unaccount_slab_page(
+unaccount_slab(
- page
+ slab
  ,...)

@ convert_list_entry @
identifier fn =~ "list_entry|list_.*_entry|list_.*_entry_or_null";
@@
-page = fn(
+slab = fn(
 ...,
- struct page
+ struct slab
,...)

@ convert_slab_pfmemmaloc @
@@
-PageSlabPfmemalloc(page)
+slab_test_pfmemalloc(slab)

@ convert_slab_clear_pfmemalloc @
@@
-ClearPageSlabPfmemalloc(page)
+slab_clear_pfmemalloc(slab)

@ convert_obj_to_index @
@@
obj_to_index(
 ...,
- page
+ slab_page(slab)
,...)

// for all functions (with exceptions), change any "struct page *page"
// parameter to "struct slab *slab" in the signature, and generally all
// occurences of "page" to "slab" in the body - with some special cases.
@ convert_param_struct_page_ptr @
identifier fn;
expression E;
@@

 fn(...,
-   struct page *page
+   struct slab *slab
    ,...)

{
<...
(
- int page_node;
+ int slab_node;
|
- page_node
+ slab_node
|
- page_slab(page)
+ slab
|
- page_address(page)
+ slab_address(slab)
|
- page_size(page)
+ slab_size(slab)
|
- page_to_nid(page)
+ slab_nid(slab)
|
- virt_to_head_page(E)
+ virt_to_slab(E)
|
- page
+ slab
)
...>
}

// rename a function parameter
@ convert_param_page_node @
identifier fn;
expression E;
@@

 fn(...,
-   int page_node
+   int slab_node
    ,...)

{
<...
- page_node
+ slab_node
...>
}

// functions converted by convert_param_struct_page_ptr that were previously
// temporarily called using slab_page(E) so we want to remove the wrapper now
// that they accept struct slab ptr directly
// XXX: could the list of names for fn be somehow autogenerated from what the
// rule convert_param_struct_page_ptr matches?
@ remove_slab_page_wrappers @
identifier fn =~ "index_to_obj";
expression E;
@@
fn(...,
- slab_page(E)
+ E
  ,...)

// similar to remove_slab_page_wrappers but we just change page to slab
@ rename_called_function_parameter @
identifier fn =~ "TODO";
@@
fn(...,
- page
+ slab
  ,...)

// functions that were returning struct page ptr and now will return struct
// slab ptr, including slab_page() wrapper removal
@ convert_return_struct_page @
identifier fn =~ "cache_grow_begin|get_valid_first_slab|get_first_slab";
expression E;
@@
static
-struct page *
+struct slab *
fn(...)
{
<...
- slab_page(E)
+ E
...>
}

// all functions (with exceptions) with a local "struct page *page" variable
// that will be renamed to "struct slab *slab", and optionally another
// temporary "struct page *" variable where we either also do a specific rename
// or keep the original name (e.g. for safe list walking) unchanged (via
// identifier tmp)
@ convert_local_struct_page @
identifier fn !~ "kmem_getpages|kmem_freepages";
identifier tmp;
expression E;
@@

 fn(...)
{
<...
(
- struct page *page;
+ struct slab *slab;
|
- struct page *tmp;
+ struct slab *tmp;
|
- page_slab(page)
+ slab
|
- page_to_nid(page)
+ slab_nid(slab)
|
- kasan_poison_slab(page)
+ kasan_poison_slab(slab_page(slab))
|
- page_address(page)
+ slab_address(slab)
|
- page_size(page)
+ slab_size(slab)
|
- page->pages
+ slab->slabs
|
- page = virt_to_head_page(E)
+ slab = virt_to_slab(E)
|
- virt_to_head_page(E)
+ virt_to_slab(E)
|
- page
+ slab
)
...>
}

