// spatch --include-headers --no-includes slub.cocci include/linux/slub_def.h mm/slub.c

// for all functions, with exceptions, change any "struct page *page"
// parameter to "struct slab *slab" in the signature, and generally all
// occurences of "page" to "slab" in the body - with some special cases.
@ rule1 @
identifier fn !~ "free_nonslab_page";
@@

 fn(...,
-   struct page *page
+   struct slab *slab
    ,...)

{
<...
(
- page_slab(page)
+ slab
|
- compound_order(page)
+ slab_order(slab)
|
- PageSlab(page)
+ PageSlab(slab_page(slab))
|
- page_address(page)
+ slab_address(slab)
|
- page_to_nid(page)
+ slab_nid(slab)
|
- page->pages
+ slab->slabs
|
- page
+ slab
)
...>
}

@ rule2 @
identifier fn;
@@

 fn(...,
-   int (*get_count)(struct page *)
+   int (*get_count)(struct slab *)
    ,...)

{
<...
- get_count(slab_page(slab))
+ get_count(slab)
...>
}

// rule2 modified for get_partial, get_any_partial, get_partial_node
@ rule2a @
identifier fn;
@@

 fn(...,
-   struct page **ret_page
+   struct slab **ret_slab
    ,...)

{
<...
- ret_page
+ ret_slab
...>
}

// rule2 modified for __unfreeze_partials
@ rule2b @
identifier fn;
@@

 fn(...,
-   struct page *partial_page
+   struct slab *partial_slab
    ,...)

{
<...
- partial_page
+ partial_slab
...>
}

// functions converted by rule1 that were temporarily called using slab_page(E)
// so we want to remove the conversion now that they accept struct slab *
// XXX: could the list of names for fn be somehow autogenerated by rule1?
@ rule3 @
identifier fn =~ "__fill_map|slab_free|do_slab_free|obj_to_index";
expression E;
@@
fn(...,
- slab_page(E)
+ E
  ,...)

// functions that were returning pointer to struct page and now will return
// pointer to struct slab
@ rule4 @
identifier fn =~ "allocate_slab|new_slab";
expression E;
@@
static
-struct page *
+struct slab *
fn(...)
{
<...
- slab_page(E)
+ E
...>
}

// specific functions with a local "struct page *page" variable that will be
// renamed to "struct slab *slab", and optionally another temporary "struct page *"
// variable (e.g. for safe list walking) where we keep the name
@ rule5 @
identifier fn =~ "validate_slab_node|__kmem_cache_do_shrink|free_partial|allocate_slab|early_kmem_cache_node_alloc|show_slab_objects|slab_alloc_node|slabs_cpu_partial_show|___slab_alloc|get_partial_node|__flush_cpu_slab|flush_slab|put_cpu_partial|__unfreeze_partials|unfreeze_partials_cpu|unfreeze_partials|rcu_free_slab";
identifier tmp;
@@

 fn(...)
{
<...
(
- struct page *page;
+ struct slab *slab;
|
- struct page *page2;
+ struct slab *slab2;
|
- struct page *flush_page;
+ struct slab *flush_slab;
|
- flush_page
+ flush_slab
|
- struct page *discard_page;
+ struct slab *slab_to_discard;
|
- discard_page
+ slab_to_discard
|
- struct page *partial_page;
+ struct slab *partial_slab;
|
- partial_page
+ partial_slab
|
- struct page *oldpage;
+ struct slab *oldslab;
|
- oldpage->pages
+ oldslab->slabs
|
- oldpage
+ oldslab
|
- struct page *page_to_unfreeze;
+ struct slab *slab_to_unfreeze;
|
- page_to_unfreeze
+ slab_to_unfreeze
|
- struct page *tmp;
+ struct slab *tmp;
|
- struct page tmp;
+ struct slab tmp;
|
- page_slab(page)
+ slab
|
- page_to_nid(page)
+ slab_nid(slab)
|
- page->pages
+ slab->slabs
|
- page2
+ slab2
|
- page
+ slab
|
- int pages;
+ int slabs;
|
- pages
+ slabs
)
...>
}

@ rule6 @
@@

struct kmem_cache_cpu {
...
-struct page *page;
+struct slab *slab;
...
-struct page *partial;
+struct slab *partial;
...
}

@ rule7 @
struct kmem_cache_cpu *c;
@@

-c->page
+c->slab

