// SLUB: mass conversion of "struct page" to "struct slab"
//
// usage:
// spatch --include-headers --no-includes slub.cocci include/linux/slub_def.h mm/slub.c

// various API changes - account_slab()
@ convert_callers_account_slab @
expression E;
@@
-account_slab_page(
+account_slab(
- page
+ slab
  ,...)

// various API changes - unaccount_slab()
@ convert_callers_unaccount_slab @
expression E;
@@
-unaccount_slab_page(
+unaccount_slab(
- page
+ slab
  ,...)

// for all functions (with exceptions), change any "struct page *page"
// parameter to "struct slab *slab" in the signature, and generally all
// occurences of "page" to "slab" in the body - with some special cases.
@ convert_param_struct_page_ptr @
identifier fn !~ "free_nonslab_page|obj_to_index|objs_per_slab_page|nearest_obj";
@@

 fn(...,
-   struct page *page
+   struct slab *slab
    ,...)

{
<...
(
- page_slab(page)
+ slab
|
- compound_order(page)
+ slab_order(slab)
|
- PageSlab(page)
+ PageSlab(slab_page(slab))
|
- page_address(page)
+ slab_address(slab)
|
- page_size(page)
+ slab_size(slab)
|
- page_to_nid(page)
+ slab_nid(slab)
|
- page->pages
+ slab->slabs
|
- page
+ slab
)
...>
}

// similar to convert_param_struct_page_ptr but the param is called
// partial_page
// XXX: is it possible to merge with convert_param_struct_page_ptr
// with some more generic rename rule?
@ convert_param_partial_page @
identifier fn;
@@

 fn(...,
-   struct page *partial_page
+   struct slab *partial_slab
    ,...)

{
<...
- partial_page
+ partial_slab
...>
}

// similar to convert_param_struct_page_ptr but for param that's a function
// pointer that takes struct page ptr to struct slab ptr
@ convert_param_get_count @
identifier fn;
@@

 fn(...,
-   int (*get_count)(struct page *)
+   int (*get_count)(struct slab *)
    ,...)

{
<...
- get_count(slab_page(slab))
+ get_count(slab)
...>
}

// similar to convert_param_struct_page_ptr but for functions that take
// pointer to struct page ptr
@ convert_param_ret_page @
identifier fn;
@@

 fn(...,
-   struct page **ret_page
+   struct slab **ret_slab
    ,...)

{
<...
- ret_page
+ ret_slab
...>
}

// functions converted by convert_param_struct_page_ptr that were previously
// temporarily called using slab_page(E) so we want to remove the wrapper now
// that they accept struct slab ptr directly
// XXX: could the list of names for fn be somehow autogenerated from what the
// rule convert_param_struct_page_ptr matches?
@ remove_slab_page_wrappers @
identifier fn =~ "__fill_map|slab_free|do_slab_free";
expression E;
@@
fn(...,
- slab_page(E)
+ E
  ,...)

// similar to remove_slab_page_wrappers but we just change page to slab
@ rename_called_function_parameter @
identifier fn =~ "slab_pad_check|check_object";
@@
fn(...,
- page
+ slab
  ,...)

// functions that were returning struct page ptr and now will return struct
// slab ptr, including slab_page() wrapper removal
@ convert_return_struct_page @
identifier fn =~ "allocate_slab|new_slab";
expression E;
@@
static
-struct page *
+struct slab *
fn(...)
{
<...
- slab_page(E)
+ E
...>
}

// specific functions with a local "struct page *page" variable that will be
// renamed to "struct slab *slab", and optionally another temporary "struct
// page *" variable where we either also do a specific rename or keep the
// original name (e.g. for safe list walking) unchanged (via identifier tmp)
@ convert_local_struct_page @
identifier fn =~ "validate_slab_node|__kmem_cache_do_shrink|free_partial|allocate_slab|early_kmem_cache_node_alloc|show_slab_objects|slab_alloc_node|slabs_cpu_partial_show|___slab_alloc|get_partial_node|__flush_cpu_slab|flush_slab|put_cpu_partial|__unfreeze_partials|unfreeze_partials_cpu|unfreeze_partials|rcu_free_slab";
identifier tmp;
@@

 fn(...)
{
<...
(
- struct page *page;
+ struct slab *slab;
|
- struct page *page2;
+ struct slab *slab2;
|
- struct page *flush_page;
+ struct slab *flush_slab;
|
- flush_page
+ flush_slab
|
- struct page *discard_page;
+ struct slab *slab_to_discard;
|
- discard_page
+ slab_to_discard
|
- struct page *partial_page;
+ struct slab *partial_slab;
|
- partial_page
+ partial_slab
|
- struct page *oldpage;
+ struct slab *oldslab;
|
- oldpage->pages
+ oldslab->slabs
|
- oldpage
+ oldslab
|
- struct page *page_to_unfreeze;
+ struct slab *slab_to_unfreeze;
|
- page_to_unfreeze
+ slab_to_unfreeze
|
- struct page *tmp;
+ struct slab *tmp;
|
- struct page tmp;
+ struct slab tmp;
|
- page_slab(page)
+ slab
|
- page_to_nid(page)
+ slab_nid(slab)
|
- kasan_poison_slab(page)
+ kasan_poison_slab(slab_page(slab))
|
- page_address(page)
+ slab_address(slab)
|
- page_size(page)
+ slab_size(slab)
|
- page->pages
+ slab->slabs
|
- page2
+ slab2
|
- page
+ slab
|
- int pages;
+ int slabs;
|
- pages
+ slabs
)
...>
}

// in struct kmem_cache_cpu, change both the types and the names from page to
// slab
@ change_types_struct_kmem_cache_cpu @
@@

struct kmem_cache_cpu {
...
-struct page *page;
+struct slab *slab;
...
-struct page *partial;
+struct slab *partial;
...
}

// there are many places that use c->page which is now c->slab thanks to
// the rule change_types_struct_kmem_cache_cpu
@ convert_kmem_cache_cpu_page_refs @
struct kmem_cache_cpu *c;
@@

-c->page
+c->slab

